apiVersion: v1
kind: Service
metadata:
  name: mavine-service
  namespace: nx
spec:
  type: NodePort
  selector:
    app: mavine-pod
  ports:
    - nodePort: 30082
      port: 8000
      targetPort: 8000
